### ISSUE TITLE
Build for Mac OS

### ISSUE THREAD

**Issue by vBrestkin** [EE-Mod-Setup/EET_Fixpack#1]
Good afternoon! You can ask you to build the assembly for Mac OS too. I really love the whole BG series and I'm tired of using emulators to run the game on a laptop.

If this is not possible - tell me how you can do it yourself. With the console I'm on You so I think I can figure it out

**Comment by RoxanneSHS** [comment]
I know absolutely nothing about Mac...I cannot provide a single idea to support that OS.
